lijst = [420, 6.9, "garnaal", 360,"zimbabwe" ]
print(lijst)
lijst.append("yo mama")
print(lijst)
lijst.clear()
print(lijst)
lijst2 = ["we back bitches", 420, 2.3]
lijst.extend(lijst2)
print(lijst)
count = lijst.count("garnaal")
print(count)
print(lijst)
x = lijst.index(420)
print (x) 
lijst.insert(0,"garnaal")
print(lijst)
lijst.pop(2)
print(lijst)
lijst.remove(2.3)
print(lijst)
lijst.reverse()
print(lijst)
lijst.sort
print(lijst)